package com.project.edugov.service;

import java.io.IOException;

import java.nio.file.Files;

import java.nio.file.Path;

import java.nio.file.Paths;

import java.nio.file.StandardCopyOption;

import java.time.Instant;

import java.util.List;

import org.springframework.beans.factory.annotation.Value;

import org.springframework.stereotype.Service;

import org.springframework.web.multipart.MultipartFile;

import com.project.edugov.exception.ResourceNotFoundException;

import com.project.edugov.model.AcademicDocument;

import com.project.edugov.model.Status;

import com.project.edugov.model.User;

import com.project.edugov.repository.AcademicDocumentRepository;

import jakarta.transaction.Transactional;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public  class AcademicDocumentServiceImpli implements AcademicDocumentService {

	private final AcademicDocumentRepository docRepo;

	@Value("${file.upload-dir}")
	private String uploadDir;

	// 1. Save Physical File (Returns the string path)
	@Override
	public String storeFile(MultipartFile file, Long userId, String userType, String docType) throws IOException {
		Path targetLocation = Paths.get(uploadDir).resolve(userType.toLowerCase()).resolve(userId.toString())
				.resolve(docType.toLowerCase());
//path is an interface here
		//paths is a utilty class 
		//paths.get() is an function that takes string and convert into  object so that java understand this as physical 
		if (!Files.exists(targetLocation)) {
			Files.createDirectories(targetLocation);
		}

		String fileName = System.currentTimeMillis() + "_" + file.getOriginalFilename();
		Path filePath = targetLocation.resolve(fileName);

		Files.copy(file.getInputStream(), filePath, StandardCopyOption.REPLACE_EXISTING);

		return filePath.toString();
	}

	@Override
	public List<AcademicDocument> getDocumentsByUser(Long userId) {
		return docRepo.findByUserUserId(userId);
	}

	// 3. FIXED: Changed getFilePath() to use getFileUrl()
	@Override
	public Path getFilePath(Long documentId) {
		AcademicDocument doc = docRepo.findById(documentId)
				.orElseThrow(() -> new ResourceNotFoundException("Document not found with ID: " + documentId));

		// Use the new getter generated by Lombok for fileUrl
		Path path = Paths.get(doc.getFileUrl());

		if (!Files.exists(path)) {
			throw new RuntimeException("File not found on disk at: " + doc.getFileUrl());
		}

		return path;
	}

	@Override
	public AcademicDocument verifyDocument(Long documentId, Status status, String notes, User admin) {
		AcademicDocument doc = docRepo.findById(documentId)
				.orElseThrow(() -> new ResourceNotFoundException("Document not found ID: " + documentId));

		doc.setVerificationStatus(status);
		doc.setNotes(notes);
		doc.setVerifiedAt(Instant.now());
		doc.setVerifiedBy(admin);

		return docRepo.save(doc);
	}

	@Override
	public AcademicDocument saveDocumentMetadata(AcademicDocument doc) {
		return docRepo.save(doc);
	}
	
	@Override
	@Transactional
	public List<AcademicDocument> verifyAllByUserId(Long userId, Status status, String notes, User admin) {
	    // Database se documents fetch karein
	    List<AcademicDocument> docs = docRepo.findByUserUserId(userId);

	    if (docs.isEmpty()) {
	        throw new ResourceNotFoundException("No documents found for User ID: " + userId);
	    }

	    // Har document ko update karein
	    docs.forEach(doc -> {
	        doc.setVerificationStatus(status);
	        doc.setNotes(notes);
	        doc.setVerifiedBy(admin);
	        doc.setVerifiedAt(Instant.now());
	    });

	    // Bulk save karein
	    return docRepo.saveAll(docs);
	}

	@Override
	@Transactional
	public AcademicDocument uploadAndSave(MultipartFile file, User user, String userType, String docType, String docNum)
			throws IOException {

		Path targetLocation = Paths.get(uploadDir).resolve(userType.toLowerCase()).resolve(user.getUserId().toString())
				.resolve(docType.toLowerCase());

		if (!Files.exists(targetLocation)) {
			Files.createDirectories(targetLocation);
		}

		String fileName = System.currentTimeMillis() + "_" + file.getOriginalFilename();
		Path filePath = targetLocation.resolve(fileName);
		Files.copy(file.getInputStream(), filePath, StandardCopyOption.REPLACE_EXISTING);

		// Build the Entity using fileUrl
		AcademicDocument doc = AcademicDocument.builder().user(user).docType(docType.toUpperCase()).docNum(docNum)
				.fileUrl(filePath.toString()) // Matches MySQL Column
				.verificationStatus(Status.PENDING).uploadedDate(Instant.now()).build();

		return docRepo.save(doc);//save document url in sql query by using insert;
	}
}