spring.application.name=EduGov
#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/EduGov
spring.datasource.username=root
spring.datasource.password=Dip@Cogn!050201
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



#hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=1234
management.endpoints.web.exposure.include=*

#Logger properties 

# 1. Specifically silence the Swagger/SpringDoc startup warnings
logging.level.org.springdoc=ERROR

# 2. Hide all background noise from Spring, Hibernate, and Tomcat
logging.level.root=WARN

# 3. Ensure YOUR project logs (the ones we just added) are still visible
logging.level.com.project.edugov=INFO

# 4. Keep Postman clean (No scary stack traces)
server.error.include-stacktrace=never