spring.application.name=EduGov
#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/EduGov
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Change the DB password per your workbench

#hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=1234
management.endpoints.web.exposure.include=*
logging.level.com.project.edugov=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
 
#For academic Documents
file.upload-dir=uploads/academicdocuments


#Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mrunalip263@gmail.com
spring.mail.password=hkjbzshfojdcccno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=mrunalip263@gmail.com
# Force timeout after 5 seconds instead of hanging infinitely
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
 
